# TAREA - TEMA 1 - PANDAS AND NUMPY
## Estudiante: Junior Sesario Huanca Acebo

## 1. Importación de librerias

Pandas y Numpy me parecen fundamentales porque facilitan mucho el manejo de datos, si hiciera esto solo con Python nativo sería más complicado

In [1]:
## os: Para manejar rutas y archivos del sistema operativo.
## numpy: Muy útil para trabajar con números, arreglos y operaciones estadísticas.
## pandas: Permite leer archivos (CSV, JSON, Excel), procesar datos y analizarlos.
## warnings: Oculta mensajes molestos de advertencias.

import os
import numpy as np
import pandas as pd

import warnings
warnings.filterwarnings('ignore')

## 2. Lectura de datos
Me parece práctico definir todas las rutas al inicio, porque así si muevo la carpeta, solo cambio DATA_PATH.

In [2]:
DATA_PATH="/Users/Junior/Downloads/ANÁLISIS DE DATOS/Logistica/Datasets/"

FILE_CUSTOMERS = 'olist_customers_dataset.csv'
FILE_GEOLOCATIONS = 'olist_geolocation_dataset.csv'
FILE_ITEMS = 'olist_order_items_dataset.csv'
FILE_PAYMENTS = 'olist_order_payments_dataset.csv'
FILE_ORDERS = 'olist_orders_dataset.csv'
FILE_STATES_ABBREVIATIONS = 'states_abbreviations.json'

## 2.1. Leemos con pandas

### 2.1.1. Archivo olist_geolocation_dataset.csv

In [3]:
## Se lee el archivo de geolocalización.
## Se fuerza que el código postal se lea como texto (str) y no como número.

geolocations = pd.read_csv(
    os.path.join(DATA_PATH, FILE_GEOLOCATIONS),
    dtype={'geolocation_zip_code_prefix': 'str'}
    )

El .head(), .info() y .describe() me ayudan a conocer rápido cómo son los datos. Es muy útil, lo usaría siempre antes de trabajar con un dataset nuevo.
Me ayudan a verificar que se leyó correctamente el archico, sin importar la extnsión que tiene.

In [4]:
geolocations.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,01037,-23.545621,-46.639292,sao paulo,SP
1,01046,-23.546081,-46.644820,sao paulo,SP
2,01046,-23.546129,-46.642951,sao paulo,SP
3,01041,-23.544392,-46.639499,sao paulo,SP
4,01035,-23.541578,-46.641607,sao paulo,SP

In [5]:
geolocations .describe()

       geolocation_lat  geolocation_lng
count     1.000163e+06     1.000163e+06
mean     -2.117615e+01    -4.639054e+01
std       5.715866e+00     4.269748e+00
min      -3.660537e+01    -1.014668e+02
25%      -2.360355e+01    -4.857317e+01
50%      -2.291938e+01    -4.663788e+01
75%      -1.997962e+01    -4.376771e+01
max       4.506593e+01     1.211054e+02

In [6]:
geolocations.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  object
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
dtypes: float64(2), object(3)
memory usage: 38.2+ MB

### 2.1.2. Archivo olist_customers_dataset

In [7]:
customers = pd.read_csv(
    os.path.join(DATA_PATH, FILE_CUSTOMERS),
    dtype={'customer_zip_code_prefix': 'str'}
)

In [8]:
## Verificar con .info() me parece una buena práctica, así sé si el archivo se cargo correctamente

customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  object
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: object(5)
memory usage: 3.8+ MB

### 2.1.3. Archivo olist_order_items_dataset

* Leemos el archivo
* Agrupamos por order_id.
* Contamos cuántos productos tiene cada orden.
* Sumamos el total de precios por orden.

In [9]:
items = pd.read_csv(
    os.path.join(DATA_PATH, FILE_ITEMS),
    dtype={'order_id': 'str'}
    )

Aquí me parece súper útil groupby. Antes lo veía complicado, pero ahora entiendo que es clave para resumir datos.

In [10]:
items_agg = items.groupby(
    ['order_id']).agg(
        # conteo de producto
        {'order_item_id': 'count',
        # suma de los precios de los artículos
        'price': 'sum'}
                      ).reset_index()

In [11]:
## Comprobamos los primeros 5 datos
items_agg.head()

                           order_id  order_item_id   price
0  00010242fe8c5a6d1ba2dd792cb16214              1   58.90
1  00018f77f2f0320c557190d7a144bdd3              1  239.90
2  000229ec398224ef6ca0657da4fc703e              1  199.00
3  00024acbcdf0a6daa1e931b038114c75              1   12.99
4  00042b26cf59d7ce69dfabb4e55b4fd9              1  199.90

Vamos a renombrar las columnas anteriores, para que sea más intuitivo su significado.
La función rename me parece interesante, ay que puedo renombrar las columnas, de acuerdo a mis gusto, para que le pueda entender mucho mejor.

In [12]:
items_agg.rename(
    columns={'order_item_id': 'total_products', 'price': 'total_sales'},
    inplace=True
    )

In [13]:
items_agg

                               order_id  total_products  total_sales
0      00010242fe8c5a6d1ba2dd792cb16214               1        58.90
1      00018f77f2f0320c557190d7a144bdd3               1       239.90
2      000229ec398224ef6ca0657da4fc703e               1       199.00
3      00024acbcdf0a6daa1e931b038114c75               1        12.99
4      00042b26cf59d7ce69dfabb4e55b4fd9               1       199.90
...                                 ...             ...          ...
98661  fffc94f6ce00a00581880bf54a75a037               1       299.99
98662  fffcd46ef2263f404302a634eb57f7eb               1       350.00
98663  fffce4705a9662cd70adb13d4a31832d               1        99.90
98664  fffe18544ffabc95dfada21779c9644f               1        55.99
98665  fffe41c64501cc87c801fd61db3f6244               1        43.00

[98666 rows x 3 columns]

### 2.1.4. olist_order_payments_dataset

In [14]:
payments = pd.read_csv(
    os.path.join(DATA_PATH, FILE_PAYMENTS),
    dtype={'order_id': 'str'}
    )

### 2.1.5. states_abbreviations

Me sorprendió que pandas también pueda leer JSON, no solo CSV. Muy útil si los datos vienen de APIs.

In [15]:
states_abbreviations = pd.read_json(
    os.path.join(DATA_PATH, FILE_STATES_ABBREVIATIONS),
    dtype={'abbreviation': 'str'}
    )

### 2.1.6. olist_orders_dataset

In [16]:
orders = pd.read_csv(
    os.path.join(DATA_PATH, FILE_ORDERS),
    dtype={'order_id': 'str'}
    )

In [17]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 9 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
 8   distance_distribution_center   96470 non-null  float64
dtypes: float64(1), object(8)
memory usage: 6.8+ MB

Convertimos varias columnas a formato fecha para hacer análisis de tiempo. Me parece muy útil porque si no convierto a fecha, no podría calcular retrasos, meses o trimestres.

In [18]:
## convierte order_purchase_timestamp
orders['order_purchase_timestamp'] = pd.to_datetime(orders['order_purchase_timestamp'], errors='coerce' )

# order_approved_at
orders['order_approved_at'] = pd.to_datetime(orders['order_approved_at'])

# order_delivered_carrier_date
orders['order_delivered_carrier_date'] = pd.to_datetime(orders['order_delivered_carrier_date'])

# order_delivered_customer_date
orders['order_delivered_customer_date'] = pd.to_datetime(orders['order_delivered_customer_date'])

# order_estimated_delivery_date
orders['order_estimated_delivery_date'] = pd.to_datetime(orders['order_estimated_delivery_date'])

In [19]:
## Ahora podemos ver como ha cambiado el formato:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 9 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
 8   distance_distribution_center   96470 non-null  float64
dtypes: datetime64[ns](5), float64(1), object(3)
memory usage: 6.8+ MB

Esto es clave, me gusta porque facilita agrupar por mes o año para ver tendencias.

In [20]:
# Define una columna con el año en que sucedió la orden
orders['year'] = orders['order_purchase_timestamp'].dt.year

# Define una columna con el mes en que sucedió la orden
orders['month'] = orders['order_purchase_timestamp'].dt.month

# Define una columna con trimestre con el que paso la orden (ej. Q12018)
# https://pandas.pydata.org/docs/reference/api/pandas.Series.dt.to_period.html
orders['quarter'] = orders['order_purchase_timestamp'].dt.to_period('Q')

# Define una columna con mes y año con el que paso la orden (ej. 02-2018)
# Hint: ¿que hace el metodo ...to_period('M')?
orders['year_month'] = orders['order_purchase_timestamp'].dt.to_period('M')

* delta_days: diferencia en días entre entrega real y estimada.
* delay_status: clasifica en a tiempo, pequeño retraso o gran retraso.
  
Esto es de lo más útil del ejercicio. Entender el retraso en días es algo que cualquier empresa necesita.

In [21]:
# Nota: tenemos que realizar la conversion de
# segundos a días

orders['delta_days'] = (
    orders['order_delivered_customer_date'] -
    orders['order_estimated_delivery_date']
    ).dt.total_seconds()/ 60 / 60 / 24

In [22]:
# Define 
orders['delay_status']  = np.where(
    orders['delta_days'] > 3, 'long_delay',
    np.where(orders['delta_days'] <= 0, 'on_time','short_delay')
    )

Para ver el efecto de lo anterior podemos extraer un muestra con la función `.sample`

### 2.1.7. olist_geolocation_dataset
Aunque anteriormente hemos leído este archivo, debemos notar que contiene información redudante de muchos codigos postales, como en el caso del valor 24220:

In [23]:
geolocations.query("geolocation_zip_code_prefix == 24220")

Empty DataFrame
Columns: [geolocation_zip_code_prefix, geolocation_lat, geolocation_lng, geolocation_city, geolocation_state]
Index: []

Para el análisis tendremos que eliminar esta duplicaciones. Esto se puede lograr con el método drop_duplicates
Me parecio muy util, porque ya no tengo que crear un algoritmo, solamente uso dicho función

In [24]:
unique_geolocations = geolocations.drop_duplicates(
    subset = ['geolocation_zip_code_prefix']
    )

In [25]:
unique_geolocations.query(
    "geolocation_zip_code_prefix == 24220"
    )

Empty DataFrame
Columns: [geolocation_zip_code_prefix, geolocation_lat, geolocation_lng, geolocation_city, geolocation_state]
Index: []

## 3. Procesamiento global

### 3.1. Clientes + geolocalización

Para unir dos fuentes de datos, podemos usar la función `.merge`. En el siguiente ejemplo se unes los datos de los clientes junto sus geolocalizaciones.

El .merge() al principio me costó entender, pero ahora lo veo como un JOIN de SQL. Es demasiado útil.

In [26]:
customers_geolocation = customers.merge(
    unique_geolocations,
    left_on='customer_zip_code_prefix',
    right_on='geolocation_zip_code_prefix',
    how='left'
)

### 3.2. Clientes + geolocalización + nombre del estado donde viven
Ahora repetiremos un proceso análogo pero con los nombres del estado donde viven los customers

In [27]:
# Une los dataframe customers_geolocation y states_abbreviations

customers_geolocation_estado = customers_geolocation.merge(
    states_abbreviations,
    left_on='geolocation_state',   # columna en customers_geolocation
    right_on='abbreviation',       # columna en states_abbreviations
    how='left'
)

In [28]:
customers_geolocation_estado

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state,abbreviation,state_name
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,14409,-20.509897,-47.397866,franca,SP,SP,São Paulo
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,09790,sao bernardo do campo,SP,09790,-23.726853,-46.545746,sao bernardo do campo,SP,SP,São Paulo
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,01151,sao paulo,SP,01151,-23.527788,-46.660310,sao paulo,SP,SP,São Paulo
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,08775,mogi das cruzes,SP,08775,-23.496930,-46.185352,mogi das cruzes,SP,SP,São Paulo
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,13056,-22.987222,-47.151073,campinas,SP,SP,São Paulo
...,...,...,...,...,...,...,...,...,...,...,...,...
99436,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,03937,sao paulo,SP,03937,-23.587901,-46.501830,são paulo,SP,SP,São Paulo
99437,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,06764,taboao da serra,SP,06764,-23.612294,-46.765787,taboao da serra,SP,SP,São Paulo
99438,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE,60115,-3.744128,-38.510859,fortaleza,CE,CE,Ceará
99439,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS,92120,-29.956391,-51.167614,canoas,RS,RS,Rio Grande do Sul
99440,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,06703,cotia,SP,06703,-23.593985,-46.910591,cotia,SP,SP,São Paulo

### 3.3. Órdenes + total de artículos y precios

In [29]:
# une los dataframe orders y items_agg por order_id
orders_totals = orders.merge(
    items_agg,
    on=['order_id'],   # columna común en ambos DataFrames
    how='left'         # conserva todas las filas de orders
)

In [30]:
orders_totals

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,distance_distribution_center,year,month,quarter,year_month,delta_days,delay_status,total_products,total_sales
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,29.84,2017,10,2017Q4,2017-10,-7.107488,on_time,1.0,29.99
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,25.53,2018,7,2018Q3,2018-07,-5.355729,on_time,1.0,118.70
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,61.56,2018,8,2018Q3,2018-08,-17.245498,on_time,1.0,159.90
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,60.30,2017,11,2017Q4,2017-11,-12.980069,on_time,1.0,45.00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,80.97,2018,2,2018Q1,2018-02,-9.238171,on_time,1.0,19.90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28,68.26,2017,3,2017Q1,2017-03,-10.369433,on_time,1.0,72.00
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,14.92,2018,2,2018Q1,2018-02,-1.265324,on_time,1.0,174.90
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,36.37,2017,8,2017Q3,2017-08,-5.524803,on_time,1.0,205.99
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,32.04,2018,1,2018Q1,2018-01,-20.018819,on_time,2.0,359.98
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,3.54,2018,3,2018Q1,2018-03,-17.452431,on_time,1.0,68.50

### 3.4 Clientes + geolocalización + nombre del estado donde viven + Órdenes + total de artículos y precios

In [31]:
results = orders_totals.merge(
    customers_geolocation_estado,
    on=['customer_id'],
    how='left'
    )

## 4. Entregables

Es increible que se pueda exportar a un documento csv, todo el analisi que se realizo. Esto se hace para un mejor entendimiento de los datos, para que se pueda entender

In [32]:
# Completa el codigo
results.to_csv(
    # nombre del archivo
    'results2.csv', 
    # flag para no escribir el indice del dataframe al csv
    index=False
    )